src/config/__init__.py, src/config/enums.py, src/helpers/task_helpers.py, src/models/student.py, src/models/test.py, src/routes/test.py, src/templates/question_pdf.html
=> offline paper checking implementation

lib/helpers/syncGSheet.js, questions/question1.md, questions/question17.md, questions/question2.md, questions/question3.md, questions/question4.md, questions/question5.md, questions/question6.md, questions/question9.md
New questions created by Vandana.
=> New Questions By Vandana

lib/helpers/syncGSheet.js, lib/services/student.js
- Added testVersion in googleSheet
- updated students.findEnrolmentKeyByKey to also return questionSet & testVersion using eager.
=> testVersion Field in GoogleSheet

lib/models/student.js
Fixed live bug now all the qualifications fields are allowed for an empty string.
=> Live Bug for #98

README.md, lib/seedQuestions/index.js, questions/config/config.json
updated config.json file except rewriting the README.md
=> updatd config.json file

lib/migrations/20190627101536_remove_typeofTest_From_students.js, lib/models/enrolmentKey.js, lib/models/student.js, lib/routes/onAssessment.js, lib/services/assessment.js, lib/services/partner.js
=> added typeOfTest column in enrolment_key table.

lib/models/student.js, lib/services/student.js
using **'/partners/{partnerId}/students'** API call we get the partner all students details. this details used for partnerDashBoard to show students totalMarks.
=> In partners API call getting students totalMarks

lib/services/exotel.js, sample.env, server/index.js
Now SMS will not be sent on a development environment.
=> SMS will be sent on production level.

lib/helpers/syncGSheet.js, lib/models/studentContact.js, lib/routes/flow.js, lib/routes/students.js, lib/services/student.js
removing the previous implementation to take students status from gSheet now it's coming from directly DB.
=> Student status using their mobile number

lib/models/enrolmentKey.js, lib/services/student.js, webapp/static/script.js
test time is increased 1 hour to 1 and a half hours.
=> Test time increased

lib/models/enrolmentKey.js, lib/services/student.js, package.json
students status using their mobile number
=> student status

webapp/static/script.js
there is an error while submitting the test now it is solved
=> Test Error solved

.eslintrc.json, lib/helpers.js, lib/models/enrolmentKey.js, lib/services/student.js
=> Upload data error

.eslintrc.json, lib/helpers/syncGSheet.js, lib/helpers/syncPartnerSheet.js, lib/migrations/templates/defaultMigrationTemplate.js
=> re-solved lint errors

lib/constants.js, lib/routes/students.js, lib/services/student.js
students details for new dash board
=> New dash board

lib/services/metrics.js
enrolment_keys table alias error is solved
=> Metrics-Related-Errror

lib/routes/students.js, lib/services/student.js
Making new end point to change student stage.
=> Change student stage

lib/migrations/20191111122321_table_for_feedbackAndnew_users.js, lib/migrations/20191205155500_add_column_for_assign_work.js, lib/models/feedback.js, lib/models/studentTransitions.js, lib/routes/feedback.js, lib/routes/students.js, lib/services/feedback.js, lib/services/user.js
=> student stage changes

lib/constants.js, lib/services/feedback.js
making some changes in back end
=> final commit for dashboard

lib/constants.js
=> updated config file

lib/services/assessment.js, server/index.js, webapp/static/script.js
=> removed some stages

lib/models/studentTransitions.js, lib/routes/feedback.js, lib/services/assessment.js, lib/services/feedback.js
=> modified some files

lib/services/student.js
=> some changes in student file

lib/services/student.js
=> minor bug is fixed

lib/routes/onAssessment.js, lib/routes/students.js, lib/services/assessment.js, webapp/index.html, webapp/static/script.js
inform online test result immediately after giving test.
=> inform online test result immediately

lib/migrations/20200329081905_addingColumn_slug_in_partnersTable.js, lib/models/partner.js, lib/routes/flow.js, lib/routes/partners.js, lib/routes/reports.js, lib/services/metrics.js, lib/services/partner.js, lib/services/student.js
make one migration for adding slug column in partners table
=> partners students online test tracking done

lib/migrations/20200406215705_add_column_for_audioRecording.js, lib/models/feedback.js, lib/routes/feedback.js, lib/routes/flow.js, lib/services/feedback.js, lib/services/student.js
audio file upload feature implemented
=> audio file upload feature implemented

lib/routes/partners.js, lib/services/student.js
partner get students details by date
=> partner get students details by date

sample.env
modified sample.env file  and medhavi branch
=> Gave stage permission to Nilam

lib/routes/feedback.js, lib/services/feedback.js, lib/services/student.js
=> New Feature.

webapp/index.html, webapp/static/script.js
boys online test closed as priority based.
=> boys test closed

lib/helpers/smsTemplates.js, lib/migrations/20200531162929_adding_column_for_tags.js, lib/models/student.js, lib/routes/partners.js, lib/routes/students.js, lib/services/assessment.js, lib/services/partner.js, lib/services/student.js, webapp/index.html, webapp/static/script.js
=> Boys Admission close

lib/services/partner.js
In partners progress made added  failed students details.
=> Adding new features

lib/constants.js, lib/helpers/smsTemplates.js, lib/migrations/20200613103324_create_field_for_contact_type.js, lib/models/studentContact.js, lib/routes/feedback.js, lib/routes/students.js, lib/services/assessment.js, lib/services/feedback.js, lib/services/student.js, server/index.js
informed students to complete test once he's stage is basic details entered after 4 hours., add/Update contact number.
=> Informed students to complete test, add/Update contact number

lib/routes/students.js, lib/services/student.js
Get student details by ID to implementing student extra details on new dashboard.
=> Get student details

lib/routes/feedback.js
=> Minor bug fixed

lib/services/assessment.js, lib/services/feedback.js, server/index.js
APIs related to exotel services still exist. Just disabled the auto sms send feature. The bug due to it also fixed. Users should be assigned to students
=> Disabled exotel sms service functions

lib/routes/student.js
Reverts navgurukul/chanakya#297
=> Revert "Dev"

webapp/static/script.js
Reverts navgurukul/chanakya#369
=> Revert "Districts"

webapp/index.html, webapp/static/script.js
Reverts navgurukul/chanakya#394
=> Revert "Added partner refer"

webapp/index.html, webapp/static/script.js
Reverts navgurukul/chanakya#399
=> Revert "Added refer_partner"

lib/routes/emailReport.js, lib/services/emailReport.js
changed the route email report  get by emailId to getBy partnerId
=> email report route updated

lib/routes/student.js, lib/services/student.js
=> updated the flag routes

webapp/index.html, webapp/static/script.js, webapp/static/style.css
* Added inline css as there is nesting of div elements
=> added inline css

webapp/index.html, webapp/static/script.js, webapp/static/style.css
Reverts navgurukul/chanakya#468
=> Revert "added inline css"

lib/helpers/partnersEmailReport.js, lib/helpers/templates/partnersReports.html, lib/migrations/20211115170830_email_report-to-partner.js, lib/models/emailreports.js, lib/routes/emailReport.js, lib/services/emailReports.js, server/index.js
partner email reports  updated
=> partner email reports 

lib/constants.js, lib/migrations/20211210164559_gender_column_interview_owners.js, lib/models/owners.js, lib/routes/owners.js, lib/services/owners.js
implemented the gender assignment work
=> implemented the gender assignment work

lib/constants.js, lib/migrations/20211216155315_gender_column_interview_owners.js, lib/models/owners.js, lib/routes/owners.js, lib/services/owners.js
Gender wise interview assigning
=> implemented the gender assignment task

lib/migrations/20211210164559_gender_column_interview_owners.js
=> test-image-update

lib/helpers/redflags.js, lib/routes/feedback.js
=> resolved some typos and bugs

lib/helpers/redflags.js, lib/services/student.js
=> fixed-bugs-in-redflags

lib/constants.js, lib/helpers/sendEmail.js, server/index.js
fixed some bugs in partners email reports
=> fixed some bugs in partners email reports

server/index.js
fixed the time in cron service
=> Bug in cron Time

lib/constants.js, lib/helpers/sendEmail.js, server/index.js
=> Bug in cron timer

lib/services/student.js
implemented the multiple-stage-filter feature
=> implemented the multiple-stage-filter feature

lib/services/student.js
removed the not in test failed stage ,student service
=> removed the not in test failed stage ,student service

lib/helpers/partnersEmailReport.js, lib/helpers/templates/partnersReports.html, server/index.js
updated partners email reports template
=> updated partners email reports template

lib/helpers/templates/partnersReports.html, lib/routes/partner.js, lib/services/partner.js, server/index.js
=> implemented the graph route

lib/migrations/20220222073028_interview-slot-table.js, lib/routes/studnetSlot.js, lib/services/studnetInterviewSlot.js
added a new route and did some fixes
=> added a new route and did some fixes

lib/routes/ownerSchedule.js, lib/services/ownerSchedule.js
fixed bugs in owners sechedule
=> fixed bugs in owners sechedule

lib/routes/studnetSlot.js, lib/services/ownerSchedule.js, lib/services/studnetInterviewSlot.js
=> removed logs

lib/routes/partner.js
Reverts navgurukul/chanakya#631
=> Revert "state comment"

lib/models/partner.js, lib/routes/partner.js, server/manifest.js
Reverts navgurukul/chanakya#638
=> Revert "fixed partners updated api"

lib/routes/student.js, lib/services/student.js
Reverts navgurukul/chanakya#675
=> Revert "payload change"

lib/routes/student.js, lib/services/student.js
Reverts navgurukul/chanakya#674
=> Revert "changes in transition delete api"

lib/constants.js, lib/migrations/20240103085930_stage_notification_latest.js, lib/models/feedback.js, lib/routes/feedback.js, lib/services/feedback.js, lib/services/send_sms.js, package.json, sms_templates/sent_stage_notification.txt
Reverts navgurukul/chanakya#701
=> Revert "Revert "Created notification feature""

lib/constants.js, lib/migrations/20240103085930_stage_notification_latest.js, lib/models/feedback.js, lib/routes/feedback.js, lib/services/feedback.js, lib/services/send_sms.js, package.json, sms_templates/sent_stage_notification.txt
Reverts navgurukul/chanakya#703
=> Revert "Revert "Revert "Revert "Created notification feature""""

lib/routes/school.js, lib/services/school.js
Reverts navgurukul/chanakya#715
=> Revert "ghar moodle changes"
